// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEf06Ev19XaG0SkFaiGHPUFO38y3XZjCI',
    appId: '1:427831978148:android:b7ca49e7c0781f5ab5de31',
    messagingSenderId: '427831978148',
    projectId: 'image-caption-9a008',
    storageBucket: 'image-caption-9a008.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvdUdt7Mvi9B_t77Aos6giPl9P8eYrRcI',
    appId: '1:427831978148:ios:8bf56028e116e01bb5de31',
    messagingSenderId: '427831978148',
    projectId: 'image-caption-9a008',
    storageBucket: 'image-caption-9a008.appspot.com',
    androidClientId: '427831978148-s4i0afoga78bkfu3e40h89n4nti69cl4.apps.googleusercontent.com',
    iosClientId: '427831978148-1hvhauetesj1kdkrnlfvuj9hcp8ncnpj.apps.googleusercontent.com',
    iosBundleId: 'com.example.tell',
  );
}
